export const Palindrome = [
    "deed",
    "kayak",
    "racecar",
    "rotator",
    "repaper",
    "noon",
    "wow",
    "madam",
    "anna",
    "civic",
    "tenet",
    "stats",
    "sagas",
    "adda",
    "mom",
    "radar",
    "solos",
    "Taco cat",
    "No lemon, no melon",
    "Never odd or even",
    "My gym",
    "Was it a cat I saw"
];